### ISSUE TITLE
Feedback from per-window supporters

### ISSUE THREAD

**Issue by hultmann** [hultmann/multifox#185]
I'm trying to gather feedback from per-window supporters about per-tab profiles. What is your workflow?

It seems stopping to reset the identity profile for new tabs could be enough. What else could be done?

**Comment by Alex-Prime91** [comment]
How I use Multifox is I run multiple roleplay profiles on Facebook, and therefore need multiple accounts open at once (usually four or five of them). For each window, I usually have multiple tabs I'm working on with that account, so having Multifox be per-tab is extremely inconvenient as it gets very muddled very fast. 

Having more windows open is easier, as I can collapse them into one should I wish it. I understand why some people would like the per-tab method, but it's inconvenient for me personally.

**Comment by buidanhnhan** [comment]
I have 5 windows at a time, each window has it's own profile name which I set as username for 3 different websites. So a total of 15 tabs excluding my main account window. 

My suggestion is keeping the "per-window" approach and add a seperated "per-tab" window.

**Comment by andrzej-r** [comment]
Ditto. I have several profiles/windows assigned to specific websites: profile 2 to webmail, profile 3 to youtube, 4 - another webmail, 5 - shopping, etc. I like "one window per identity" mode because I use multifox for privacy, not for a way of accessing several online accounts simultaneously.

It would be nice to assign names to that profiles and be able to open them at random, rather than in order, as it is now.

Also, after upgrading to 3.0.0 I am no longer able open a new "empty" window (C-A-m) with a new profile. Instead, the current window with all its contents switches to the new identity, which almost never is what I intended and may(?) cause identity leaks.

**Comment by hultmann** [comment]
OK folks, "Window Mode" option is coming in a few hours. I already have a working version of it.

**Comment by hultmann** [comment]
BTW, if you middle-click a profile in Multifox 3 a new tab will be opened instead of reloading the current one. It is not obvious but it is consistent with Firefox's behavior.

**Comment by hultmann** [comment]
Multifox 3.1b1 available! It probably still needs some polish, but it works.
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by hposca** [comment]
Hi!
I updated to the latest version (3.1b1) to get back the window mode, but it didn't work as expected.
I had one gmail account open, them when I clicked on "new" it opened a new window, but with the same gmail account.
I had to downgrade to version 2.2.1 to get the old, working, behavior back!
(My ff version is 33.0.5)
Thanks, and keep doing the great work!

**Comment by hultmann** [comment]
@hposca oops, I'm restoring the old behavior.

**Comment by hultmann** [comment]
Done (3.1b2) https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by ourbob1** [comment]
thank you for restoring the per window feature. i am a system admin working with a saas solution. i have to be in different parts of the same app at the same time. without this extension i have to do this with multiple browser since the cookies from different windows in the same browser step on each other. 
i use the multifox toolbar button to switch back and forth between my open windows to keep myself organized.

**Comment by hposca** [comment]
@hultmann , thanks for the fast reply!
Unfortunately, for  me, the behavior is still the same :/ (So, for the moment, I still stay with 2.2.1)
Is there anything I can provide you to help diagnose this?

Thanks

**Comment by darkfur93** [comment]
I prefer window mode. Downloaded 3.1b2 and clicked the option in about:addons. 
Window mode should be default with a option for tab mode.

**Comment by hultmann** [comment]
@darkfur93  could you reproduce the bug mentioned by @hposca?

**Comment by darkfur93** [comment]
@hultmann When tab mode was enabled I had to refresh the page to show the new profile. Eg. When I was on my first Twitter account I clicked on Profile 2 and the same Twitter account would still be there. 

Window mode is working fine for me. Haven't had to refresh a page.

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by Komptrman** [comment]
I'm having a problem with the 3.0.0 version on restore of previous session. The first tab of a window will restore to the proper profile, but all other tabs will not restore to their previous profile. For example, Window 2 may have Tab 1 as profile 2, Tab 2 as profile 3, and Tab 3 as profile 4. Upon restore of a previous session, Tab 1 will be profile 2, and all other tabs might be profile 6. The profile of the other tabs is different on different computers. But they all exhibit the same problem with additional tabs not restoring to the proper profile from the last session.

This problem is showing up on FF for Linux and Windows7.

New Issue #189 opened.

**Comment by hultmann** [comment]
People who have problems with Window Mode (Multifox only opens the default profile):

Could you list the extensions you are using? I'm trying to reproduce the bug locally. Thanks

**Comment by hultmann** [comment]
@Komptrman please file a new issue.

**Comment by ACGicomer** [comment]
3.1.0b2 ALWAYS opens a new window when switching profiles if the window mode is turned on.  I prefer the old behavior which opened a new window only if a window for the profile doesn't exists and switches to the profile window if it does

**Comment by hposca** [comment]
Hi @hultmann , I'll describe the workflow that I used a lot (version 2) and that I tought the "window mode" in version 3 would be.

I have about 4 different gmail accounts (work, personal, mail lists, etc.).
And I use them to log into different services, like github, trello, slack, amazon, etc. each one with a different profile.
Initially I'd open a new firefox, log into one gmail account, then to the other services. To log into the other services I'd simply open new tabs and enter the service site.
Them I'd push "ctrl + alt + m" to open a new profile in a new firefox window and repeat the process.

To achieve something like this with version 3.1.0b2 I have to use the "tab profile".
I open firefox, then log into gmail, open a new tab ensuring that I'm using the profile on the gmail tab and log into the other service, open a new tab ensuring that I'm using the profile on the gmail tab and log into the other service, and so on. 
Then I have to open a new tab, drag and drop it to create a new window, change to another profile, log into the different gmail account and repeat the opening-ensuring process per tab.

And this is very tedious, error prone and takes too much more time :/
And I had to use this solution because sites like trello and slack had problems using version 2 with many profiles :/

Hope it helps a little.
Thanks

**Comment by hultmann** [comment]
3.1 beta 3 is now available: https://addons.mozilla.org/firefox/addon/multifox/versions/

Fixed: Multifox only opens the default profile
Fixed: Selecting a profile now switches between windows

**Comment by hposca** [comment]
@hultmann wonderful!!!
Now it is working "the old way" again :)
Thank you very much!

**Comment by k-bx** [comment]
Hi! Thanks for a wonderful extension. The new per-tab identities feature is awesome, it lets you easily have "lightweight" identity being open just in tab, not in whole window. Very useful for something like temporary gmail account etc. I would like to use this one.

My standard workflow is a bit more per-window. I have 2 windows, one for my personal life and another for my work-life (with it's multifox identity). It's very convenient to have those.

So, what I would like in the end is the ability to use both of features (per-window and per-tab).

Question: is it possible to make firefox open a new tab in the same profile in which currently-opened tab is? That would let me just open new window, switch it's tab to profile I need and get a multi-window experience without loosing a profile-per-tab one.

Hope this makes sense. Thanks!

**Comment by hultmann** [comment]
> Question: is it possible to make firefox open a new tab in the same profile in which currently-opened tab is? That would let me just open new window, switch it's tab to profile I need and get a multi-window experience without loosing a profile-per-tab one.

@k-bx There is a workaround: open about:config and change browser.newtab.url to about:blank, Multifox will fail to detect new tabs and it will keep the identity (it's actually a bug I may fix eventually).

==> closing this, fixed in 3.1

**Comment by k-bx** [comment]
@hultmann that is so great, everything I needed. Thanks!

**Comment by andrzej-r** [comment]
In 3.1 "New Identity Profile" (C-A-m) opens a new profile with the number higher by 1 than _ever_ used. So currently my multifox menu shows a list of 23 profiles (the number keeps growing every time I mistakenly press C-A-m, even if I have never used most of these profiles). This shortcut used to open the next available profile (higher by 1 than the highest profile _currently_ used).

At the moment, Multifox is lacking an ability to quickly open previously used profiles. Ideally, it should have a shortcut to open an Nth profile, or at least the next available one, as C-A-m used to do. "New Identity Profile" as currently implemented does not really need a shortcut.

Also, since profiles are now persistent, there should be a way of deleting them.

**Comment by ACGicomer** [comment]
@andrzej-r, didn't know there used to be a 'higher by 1' shortcut functionality. I'd like that better as well. Even better would be "1st unopened". If profile 1 and 3 had open windows it could open a new profile 2 window/tab. Better yet would be configurable options between the three.

I had a similar problem before I realized the shortcut was creating new profiles. But there is a delete option. There's an edit on the toolbar that allows deletion. Of course, an end masse option would be nice since you have (and I had) so many.

**Comment by k-bx** [comment]
@hultmann updated to latest FireFox and your suggestion stopped working! When I open a new tab it doesn't open in the same profile as current one chosen. Please help!

**Comment by hultmann** [comment]
It's #203, update Multifox (v3.2) to fix that. :)
